# Generated by Django 5.2 on 2025-04-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
