# Generated by Django 5.1.6 on 2025-04-10 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_comment"),
        ("posts", "0003_delete_follow"),
    ]

    operations = []
