# Generated by Django 5.2 on 2025-04-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_follow'),
        ('authentication', '0006_customuser_date_joined'),
    ]

    operations = [
    ]
